/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** 单账号密码登录，签发 Bearer token */
        post: operations["login"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 当前账号信息（永不含 password_hash） */
        get: operations["getMe"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/customers": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 客户列表（q 匹配 display_name/real_name/phone/identity.handle） */
        get: operations["listCustomers"];
        put?: never;
        /** 30 秒建档端点（仅 3-4 项必填） */
        post: operations["createCustomer"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/customers/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 客户详情（含 identities、notes 倒序、referrer 摘要） */
        get: operations["getCustomer"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** 渐进补全任意字段；{status:archived} 即归档（§4.2） */
        patch: operations["updateCustomer"];
        trace?: never;
    };
    "/customers/{id}/identities": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** 追加社交身份 */
        post: operations["addCustomerIdentity"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/customers/{id}/identities/{identity_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** 删除社交身份 */
        delete: operations["deleteCustomerIdentity"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/customers/{id}/notes": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** 追加客户备注 */
        post: operations["addCustomerNote"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/customers/{id}/merge": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** 把 source 客户 merge 进当前客户（语义见 §4.2） */
        post: operations["mergeCustomer"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/packages": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 套系列表（?status=active 供下单选择） */
        get: operations["listPackages"];
        put?: never;
        /** 新建套系 */
        post: operations["createPackage"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/packages/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** 更新套系；归档 = PATCH {status:archived}（无 in-use 校验，§4.3） */
        patch: operations["updatePackage"];
        trace?: never;
    };
    "/orders": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 订单列表 */
        get: operations["listOrders"];
        put?: never;
        /** 新建订单（status=consulting） */
        post: operations["createOrder"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/orders/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** 状态跃迁与字段修正（状态机语义见 §4.2） */
        patch: operations["updateOrder"];
        trace?: never;
    };
    "/schedule/slots": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 档期区间查询（含跨界 slot） */
        get: operations["listScheduleSlots"];
        put?: never;
        /** 新建档期（重叠不阻止，返回 overlaps 由前端提示） */
        post: operations["createScheduleSlot"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/schedule/slots/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** 删除档期（不自动变更订单状态，§4.2） */
        delete: operations["deleteScheduleSlot"];
        options?: never;
        head?: never;
        /** 更新档期 */
        patch: operations["updateScheduleSlot"];
        trace?: never;
    };
    "/reminders": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 提醒列表 */
        get: operations["listReminders"];
        put?: never;
        /** 手工创建自定义提醒 */
        post: operations["createReminder"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/reminders/{id}/done": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** 标记提醒完成 */
        post: operations["markReminderDone"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/reminders/{id}/dismiss": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** 忽略提醒 */
        post: operations["dismissReminder"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/reminders/scan": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** 提醒扫描唯一手动触发入口（每日定时与手动共用，鉴权同 §4.1） */
        post: operations["scanReminders"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/settings": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 读取设置 */
        get: operations["getSettings"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** 更新设置 */
        patch: operations["updateSettings"];
        trace?: never;
    };
    "/settings/telegram/bind-token": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** 生成 TG 绑定 token 与 deep link（绑定流程见 §4.5） */
        post: operations["createTelegramBindToken"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/dashboard": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 今日经营台聚合（口径单点在服务端，§4.3） */
        get: operations["getDashboard"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/export": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 全量导出（application/json 附件；counts 必须与各数组长度一致，§4.6） */
        get: operations["exportAll"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** @description 统一错误封套（§4.1）；错误码 validation_failed | unauthorized | not_found | conflict 子码 | internal */
        ErrorEnvelope: {
            error: {
                code: string;
                message: string;
            };
        };
        /** @description 账号（摄影师）；永不含 password_hash */
        Account: {
            readonly id: string;
            /** Format: date-time */
            readonly created_at: string;
        };
        /** @description 生日特例："MM-DD" 或 "YYYY-MM-DD"（年份可缺，§4.1） */
        Birthday: string;
        /** @enum {string} */
        CustomerChannel: "xiaohongshu" | "douyin" | "weibo" | "referral" | "other";
        /** @enum {string} */
        CustomerStatus: "active" | "merged" | "archived";
        /** @enum {string} */
        SocialPlatform: "wechat" | "qq" | "telegram" | "xiaohongshu" | "douyin" | "weibo" | "other";
        /** @enum {string} */
        ShootType: "portrait" | "cosplay" | "other";
        /** @enum {string} */
        PricingMode: "per_duration" | "per_photo" | "fixed";
        /** @enum {string} */
        PackageStatus: "active" | "archived";
        /**
         * @description 语义与合法跃迁见 §4.2 订单状态机
         * @enum {string}
         */
        OrderStatus: "consulting" | "scheduled" | "shot" | "selected" | "retouching" | "delivered" | "closed" | "cancelled";
        /** @enum {string} */
        SlotType: "shoot" | "hold" | "busy";
        /** @enum {string} */
        ReminderType: "birthday" | "follow_up" | "churn" | "custom";
        /** @enum {string} */
        ReminderStatus: "pending" | "done" | "dismissed";
        Customer: {
            readonly id: string;
            /** @description 服务端由账号上下文写入，客户端永不传（ADR-001） */
            readonly account_id: string;
            /** Format: date-time */
            readonly created_at: string;
            display_name: string;
            real_name?: string;
            phone?: string;
            birthday?: components["schemas"]["Birthday"];
            channel: components["schemas"]["CustomerChannel"];
            /** @description channel=referral 时必填 */
            referrer_customer_id?: string;
            status: components["schemas"]["CustomerStatus"];
            readonly merged_into_customer_id?: string;
        };
        CustomerListItem: components["schemas"]["Customer"] & {
            /** @description 非 cancelled 订单计数；order 域未落地前恒为 0 */
            orders_count: number;
            /**
             * Format: date
             * @description 非 cancelled 订单 max(shot_at) 按账号时区截断；order 域未落地前恒为 null
             */
            last_shot_at: string | null;
        };
        CustomerSummary: {
            id: string;
            display_name: string;
            channel: components["schemas"]["CustomerChannel"];
            status: components["schemas"]["CustomerStatus"];
        };
        CustomerStats: {
            /** @description 非 cancelled 订单计数；order 域未落地前恒为 0 */
            orders_count: number;
            /** @description 分；非 cancelled 订单 price 之和；order 域未落地前恒为 0 */
            total_order_amount: number;
            /**
             * Format: date
             * @description 口径同 CustomerListItem.last_shot_at
             */
            last_shot_at: string | null;
        };
        CustomerDetail: components["schemas"]["Customer"] & {
            identities: components["schemas"]["SocialIdentity"][];
            /** @description 倒序 */
            notes: components["schemas"]["CustomerNote"][];
            referrer: components["schemas"]["CustomerSummary"] | null;
            stats: components["schemas"]["CustomerStats"];
        };
        SocialIdentity: {
            readonly id: string;
            /** @description 服务端由账号上下文写入，客户端永不传（ADR-001） */
            readonly account_id: string;
            /** Format: date-time */
            readonly created_at: string;
            customer_id: string;
            platform: components["schemas"]["SocialPlatform"];
            handle: string;
            remark?: string;
        };
        CustomerNote: {
            readonly id: string;
            /** @description 服务端由账号上下文写入，客户端永不传（ADR-001） */
            readonly account_id: string;
            /** Format: date-time */
            readonly created_at: string;
            customer_id: string;
            content: string;
        };
        PackageInput: {
            name: string;
            shoot_type: components["schemas"]["ShootType"];
            pricing_mode: components["schemas"]["PricingMode"];
            /** @description 分 */
            base_price: number;
            duration_minutes?: number;
            shot_count_min?: number;
            shot_count_max?: number;
            raw_delivery_count?: number;
            /** @description 0=不含精修 */
            retouch_count?: number;
            note?: string;
        };
        Package: components["schemas"]["PackageInput"] & {
            readonly id: string;
            /** @description 服务端由账号上下文写入，客户端永不传（ADR-001） */
            readonly account_id: string;
            /** Format: date-time */
            readonly created_at: string;
            status: components["schemas"]["PackageStatus"];
        };
        PackageListItem: components["schemas"]["Package"] & {
            /** @description 引用本套系的非 cancelled 订单计数；order 域未落地前恒为 0 */
            orders_count: number;
        };
        Order: {
            readonly id: string;
            /** @description 服务端由账号上下文写入，客户端永不传（ADR-001） */
            readonly account_id: string;
            /** Format: date-time */
            readonly created_at: string;
            customer_id: string;
            package_id?: string;
            title?: string;
            status: components["schemas"]["OrderStatus"];
            /** @description 分 */
            price?: number;
            /** @default false */
            deposit_paid: boolean;
            /** @default false */
            balance_paid: boolean;
            /**
             * Format: date-time
             * @description 进入 shot 时服务端自动写入，事后可 PATCH 修正（§4.2）
             */
            shot_at?: string;
            /**
             * Format: date-time
             * @description 进入 delivered 时服务端自动写入，事后可 PATCH 修正（§4.2）
             */
            delivered_at?: string;
            note?: string;
        };
        ScheduleSlot: {
            readonly id: string;
            /** @description 服务端由账号上下文写入，客户端永不传（ADR-001） */
            readonly account_id: string;
            /** Format: date-time */
            readonly created_at: string;
            /** Format: date-time */
            start_at: string;
            /**
             * Format: date-time
             * @description 必须 > start_at
             */
            end_at: string;
            type: components["schemas"]["SlotType"];
            /** @description type=shoot 时必填 */
            order_id?: string;
            note?: string;
        };
        Reminder: {
            readonly id: string;
            /** @description 服务端由账号上下文写入，客户端永不传（ADR-001） */
            readonly account_id: string;
            /** Format: date-time */
            readonly created_at: string;
            type: components["schemas"]["ReminderType"];
            customer_id?: string;
            order_id?: string;
            /** Format: date */
            due_date: string;
            content: string;
            status: components["schemas"]["ReminderStatus"];
            /** @description unique per account（规则见 §4.4） */
            dedup_key: string;
        };
        ChurnThreshold: {
            shoot_type: components["schemas"]["ShootType"];
            days: number;
        };
        Settings: {
            /** @description IANA，默认 Asia/Shanghai；所有 date-only 判定按此时区（§4.1） */
            timezone: string;
            /** @default 3 */
            birthday_lead_days: number;
            /** @default 7 */
            follow_up_after_days: number;
            /** @description 默认全类型 180 */
            churn_thresholds: components["schemas"]["ChurnThreshold"][];
            /**
             * @description 按 timezone
             * @default 9
             */
            digest_hour: number;
            telegram_chat_id?: string;
        };
    };
    responses: {
        /** @description 400 validation_failed */
        ValidationFailed: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorEnvelope"];
            };
        };
        /** @description 401 unauthorized */
        Unauthorized: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorEnvelope"];
            };
        };
        /** @description 404 not_found */
        NotFound: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorEnvelope"];
            };
        };
        /** @description 500 internal */
        Internal: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorEnvelope"];
            };
        };
    };
    parameters: {
        Id: string;
        Page: number;
        PageSize: number;
    };
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    login: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    password: string;
                };
            };
        };
        responses: {
            /** @description 登录成功 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        token: string;
                    };
                };
            };
            400: components["responses"]["ValidationFailed"];
            401: components["responses"]["Unauthorized"];
            500: components["responses"]["Internal"];
        };
    };
    getMe: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 当前账号 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Account"];
                };
            };
            401: components["responses"]["Unauthorized"];
            500: components["responses"]["Internal"];
        };
    };
    listCustomers: {
        parameters: {
            query?: {
                q?: string;
                channel?: components["schemas"]["CustomerChannel"];
                /** @description 缺省 active；可显式查 archived/all（§4.2 归档语义） */
                status?: "active" | "merged" | "archived" | "all";
                page?: components["parameters"]["Page"];
                page_size?: components["parameters"]["PageSize"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 分页客户列表 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        items: components["schemas"]["CustomerListItem"][];
                        total: number;
                    };
                };
            };
            400: components["responses"]["ValidationFailed"];
            401: components["responses"]["Unauthorized"];
            500: components["responses"]["Internal"];
        };
    };
    createCustomer: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    display_name: string;
                    channel: components["schemas"]["CustomerChannel"];
                    /** @description channel=referral 时必填 */
                    referrer_customer_id?: string;
                    identities: {
                        platform: components["schemas"]["SocialPlatform"];
                        handle: string;
                        remark?: string;
                    }[];
                };
            };
        };
        responses: {
            /** @description 已建档 */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Customer"];
                };
            };
            400: components["responses"]["ValidationFailed"];
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
            500: components["responses"]["Internal"];
        };
    };
    getCustomer: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["Id"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 客户详情 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CustomerDetail"];
                };
            };
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
            500: components["responses"]["Internal"];
        };
    };
    updateCustomer: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["Id"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    display_name?: string;
                    real_name?: string;
                    phone?: string;
                    birthday?: components["schemas"]["Birthday"];
                    channel?: components["schemas"]["CustomerChannel"];
                    referrer_customer_id?: string;
                    status?: components["schemas"]["CustomerStatus"];
                };
            };
        };
        responses: {
            /** @description 更新后的客户 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Customer"];
                };
            };
            400: components["responses"]["ValidationFailed"];
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
            500: components["responses"]["Internal"];
        };
    };
    addCustomerIdentity: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["Id"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    platform: components["schemas"]["SocialPlatform"];
                    handle: string;
                    remark?: string;
                };
            };
        };
        responses: {
            /** @description 已追加 */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SocialIdentity"];
                };
            };
            400: components["responses"]["ValidationFailed"];
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
            500: components["responses"]["Internal"];
        };
    };
    deleteCustomerIdentity: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["Id"];
                identity_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 已删除 */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
            500: components["responses"]["Internal"];
        };
    };
    addCustomerNote: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["Id"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    content: string;
                };
            };
        };
        responses: {
            /** @description 已追加 */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CustomerNote"];
                };
            };
            400: components["responses"]["ValidationFailed"];
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
            500: components["responses"]["Internal"];
        };
    };
    mergeCustomer: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["Id"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    source_customer_id: string;
                };
            };
        };
        responses: {
            /** @description merge 后的 target 客户 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Customer"];
                };
            };
            400: components["responses"]["ValidationFailed"];
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
            /** @description merge_conflict（source 非 active） */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            500: components["responses"]["Internal"];
        };
    };
    listPackages: {
        parameters: {
            query?: {
                status?: components["schemas"]["PackageStatus"];
                page?: components["parameters"]["Page"];
                page_size?: components["parameters"]["PageSize"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 分页套系列表 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        items: components["schemas"]["PackageListItem"][];
                        total: number;
                    };
                };
            };
            400: components["responses"]["ValidationFailed"];
            401: components["responses"]["Unauthorized"];
            500: components["responses"]["Internal"];
        };
    };
    createPackage: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PackageInput"];
            };
        };
        responses: {
            /** @description 已创建 */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Package"];
                };
            };
            400: components["responses"]["ValidationFailed"];
            401: components["responses"]["Unauthorized"];
            500: components["responses"]["Internal"];
        };
    };
    updatePackage: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["Id"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    name?: string;
                    shoot_type?: components["schemas"]["ShootType"];
                    pricing_mode?: components["schemas"]["PricingMode"];
                    /** @description 分 */
                    base_price?: number;
                    duration_minutes?: number;
                    shot_count_min?: number;
                    shot_count_max?: number;
                    raw_delivery_count?: number;
                    /** @description 0=不含精修 */
                    retouch_count?: number;
                    status?: components["schemas"]["PackageStatus"];
                };
            };
        };
        responses: {
            /** @description 更新后的套系 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Package"];
                };
            };
            400: components["responses"]["ValidationFailed"];
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
            500: components["responses"]["Internal"];
        };
    };
    listOrders: {
        parameters: {
            query?: {
                customer_id?: string;
                status?: components["schemas"]["OrderStatus"];
                unpaid_balance?: boolean;
                page?: components["parameters"]["Page"];
                page_size?: components["parameters"]["PageSize"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 分页订单列表 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        items: components["schemas"]["Order"][];
                        total: number;
                    };
                };
            };
            400: components["responses"]["ValidationFailed"];
            401: components["responses"]["Unauthorized"];
            500: components["responses"]["Internal"];
        };
    };
    createOrder: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    customer_id: string;
                    package_id?: string;
                    title?: string;
                    /** @description 分 */
                    price?: number;
                };
            };
        };
        responses: {
            /** @description 已创建 */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Order"];
                };
            };
            400: components["responses"]["ValidationFailed"];
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
            /** @description customer_archived（引用 merged/archived 客户） */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            500: components["responses"]["Internal"];
        };
    };
    updateOrder: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["Id"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    status?: components["schemas"]["OrderStatus"];
                    deposit_paid?: boolean;
                    balance_paid?: boolean;
                    /** Format: date-time */
                    shot_at?: string;
                    /** Format: date-time */
                    delivered_at?: string;
                    title?: string;
                    /** @description 分 */
                    price?: number;
                    note?: string;
                };
            };
        };
        responses: {
            /** @description 更新后的订单 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Order"];
                };
            };
            400: components["responses"]["ValidationFailed"];
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
            /** @description invalid_status_transition（非法跃迁）| unpaid_balance（未结清进 closed） */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            500: components["responses"]["Internal"];
        };
    };
    listScheduleSlots: {
        parameters: {
            query: {
                from: string;
                to: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 区间内档期 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ScheduleSlot"][];
                };
            };
            400: components["responses"]["ValidationFailed"];
            401: components["responses"]["Unauthorized"];
            500: components["responses"]["Internal"];
        };
    };
    createScheduleSlot: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    /** Format: date-time */
                    start_at: string;
                    /** Format: date-time */
                    end_at: string;
                    type: components["schemas"]["SlotType"];
                    /** @description type=shoot 时必填 */
                    order_id?: string;
                    note?: string;
                };
            };
        };
        responses: {
            /** @description 已创建（含重叠提示） */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        slot: components["schemas"]["ScheduleSlot"];
                        /** @description 与新 slot 重叠的 slot_id 列表 */
                        overlaps: string[];
                    };
                };
            };
            400: components["responses"]["ValidationFailed"];
            401: components["responses"]["Unauthorized"];
            500: components["responses"]["Internal"];
        };
    };
    deleteScheduleSlot: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["Id"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 已删除 */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
            500: components["responses"]["Internal"];
        };
    };
    updateScheduleSlot: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["Id"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    /** Format: date-time */
                    start_at?: string;
                    /** Format: date-time */
                    end_at?: string;
                    type?: components["schemas"]["SlotType"];
                    order_id?: string;
                    note?: string;
                };
            };
        };
        responses: {
            /** @description 更新后的档期 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ScheduleSlot"];
                };
            };
            400: components["responses"]["ValidationFailed"];
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
            500: components["responses"]["Internal"];
        };
    };
    listReminders: {
        parameters: {
            query?: {
                status?: components["schemas"]["ReminderStatus"];
                customer_id?: string;
                due_before?: string;
                page?: components["parameters"]["Page"];
                page_size?: components["parameters"]["PageSize"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 分页提醒列表 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        items: components["schemas"]["Reminder"][];
                        total: number;
                    };
                };
            };
            400: components["responses"]["ValidationFailed"];
            401: components["responses"]["Unauthorized"];
            500: components["responses"]["Internal"];
        };
    };
    createReminder: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    /** @enum {string} */
                    type: "custom";
                    customer_id?: string;
                    /** Format: date */
                    due_date: string;
                    content: string;
                };
            };
        };
        responses: {
            /** @description 已创建 */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Reminder"];
                };
            };
            400: components["responses"]["ValidationFailed"];
            401: components["responses"]["Unauthorized"];
            500: components["responses"]["Internal"];
        };
    };
    markReminderDone: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["Id"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 更新后的提醒 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Reminder"];
                };
            };
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
            500: components["responses"]["Internal"];
        };
    };
    dismissReminder: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["Id"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 更新后的提醒 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Reminder"];
                };
            };
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
            500: components["responses"]["Internal"];
        };
    };
    scanReminders: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": {
                    /**
                     * Format: date
                     * @description 缺省=账号时区今日
                     */
                    date?: string;
                };
            };
        };
        responses: {
            /** @description 扫描结果计数 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        created: number;
                        skipped: number;
                        auto_dismissed: number;
                    };
                };
            };
            400: components["responses"]["ValidationFailed"];
            401: components["responses"]["Unauthorized"];
            500: components["responses"]["Internal"];
        };
    };
    getSettings: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 当前设置 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Settings"];
                };
            };
            401: components["responses"]["Unauthorized"];
            500: components["responses"]["Internal"];
        };
    };
    updateSettings: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    /** @description IANA 时区 */
                    timezone?: string;
                    birthday_lead_days?: number;
                    follow_up_after_days?: number;
                    churn_thresholds?: components["schemas"]["ChurnThreshold"][];
                    digest_hour?: number;
                };
            };
        };
        responses: {
            /** @description 更新后的设置 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Settings"];
                };
            };
            400: components["responses"]["ValidationFailed"];
            401: components["responses"]["Unauthorized"];
            500: components["responses"]["Internal"];
        };
    };
    createTelegramBindToken: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 绑定 token（10min 有效） */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        token: string;
                        deep_link: string;
                    };
                };
            };
            401: components["responses"]["Unauthorized"];
            500: components["responses"]["Internal"];
        };
    };
    getDashboard: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 聚合数据 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @description due_date ≤ 账号时区今日+2 天且 pending（近 3 天窗口含逾期） */
                        due_reminders: components["schemas"]["Reminder"][];
                        /** @description 今日档期（含订单+客户摘要，字段由 dashboard-today feature 细化） */
                        today_slots: components["schemas"]["ScheduleSlot"][];
                        unpaid_orders: {
                            count: number;
                            /** @description status=delivered 且 balance_paid=false（closed 必已结清故不出现） */
                            items: components["schemas"]["Order"][];
                        };
                        /** @description type=churn 且 pending */
                        churn_alerts: components["schemas"]["Reminder"][];
                        recent_stats: {
                            /** @description 近 30 天内按 created_at 统计，含全部状态 */
                            orders_created: number;
                            /** @description 近 30 天内按 delivered_at 统计，排除当前 status=cancelled */
                            orders_delivered: number;
                            /** @description 分；近 30 天 delivered_at 落窗口、balance_paid=true 且当前非 cancelled 的订单 price 之和 */
                            revenue_confirmed: number;
                        };
                    };
                };
            };
            401: components["responses"]["Unauthorized"];
            500: components["responses"]["Internal"];
        };
    };
    exportAll: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 全量导出文件（Content-Disposition 附件） */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** Format: date-time */
                        exported_at: string;
                        /** @enum {integer} */
                        schema_version: 1;
                        counts: {
                            customers: number;
                            social_identities: number;
                            customer_notes: number;
                            packages: number;
                            orders: number;
                            schedule_slots: number;
                            reminders: number;
                        };
                        customers: components["schemas"]["Customer"][];
                        social_identities: components["schemas"]["SocialIdentity"][];
                        customer_notes: components["schemas"]["CustomerNote"][];
                        packages: components["schemas"]["Package"][];
                        orders: components["schemas"]["Order"][];
                        schedule_slots: components["schemas"]["ScheduleSlot"][];
                        reminders: components["schemas"]["Reminder"][];
                        settings: components["schemas"]["Settings"];
                    };
                };
            };
            401: components["responses"]["Unauthorized"];
            500: components["responses"]["Internal"];
        };
    };
}
