import assert from 'node:assert/strict'
import { mkdir, writeFile } from 'node:fs/promises'
import { chromium } from 'playwright'

const output = process.env.CREATIVE_QA_OUTPUT_DIR ?? '/tmp/creative-foundation-qa'
await mkdir(output, { recursive: true })
const browser = await chromium.launch({ headless: true })
try {
  const page = await browser.newPage({ viewport: { width: 1440, height: 900 } })
  const errors = [], apiRequests = []
  page.on('pageerror', e => errors.push(e.message))
  page.on('request', r => { if (r.url().includes('/api/')) apiRequests.push(r.url()) })
  await page.goto(process.env.CREATIVE_LAB_URL ?? 'http://127.0.0.1:5174/creative-lab.html')
  const node = id => page.locator(`.react-flow__node[data-id="${id}"]`)
  await node('light').waitFor()
  const viewport = () => page.locator('.react-flow__viewport').getAttribute('style')
  const drag = async (a, b, button = 'left') => { await page.mouse.move(a.x,a.y); await page.mouse.down({ button }); await page.mouse.move(b.x,b.y,{steps:12}); await page.mouse.up({button}) }
  const transform = () => page.locator('.react-flow__viewport').evaluate(el => {
    const m = new DOMMatrix(getComputedStyle(el).transform)
    return { x: m.e, y: m.f, scale: m.a }
  })
  await page.mouse.move(800, 650)
  const beforeWheel = await transform()
  await page.mouse.wheel(0, 100)
  await page.waitForTimeout(200)
  const afterWheel = await transform()
  assert.equal(afterWheel.scale, beforeWheel.scale, 'plain wheel must not zoom')
  assert.equal(afterWheel.x, beforeWheel.x, 'plain vertical wheel keeps x')
  assert(afterWheel.y < beforeWheel.y, 'plain wheel scrolls canvas vertically')
  for (const modifier of ['Control', 'Meta']) {
    const beforeZoom = await transform()
    await page.keyboard.down(modifier)
    await page.mouse.wheel(0, -12)
    await page.waitForTimeout(200)
    await page.keyboard.up(modifier)
    const afterZoom = await transform()
    assert(afterZoom.scale > beforeZoom.scale, `${modifier}+wheel zooms canvas`)
    await page.mouse.wheel(0, 60)
    await page.waitForTimeout(200)
    const released = await transform()
    assert.equal(released.scale, afterZoom.scale, 'releasing modifier restores wheel scrolling')
    assert(released.y < afterZoom.y, 'scrolling resumes after modifier release')
  }
  await page.getByRole('button',{name:'分组样例',exact:true}).click()
  await page.waitForTimeout(250)
  const beforeViewport = await viewport()
  await drag({x:25,y:105},{x:630,y:760})
  assert.equal(await viewport(), beforeViewport, 'left drag must select rather than pan')
  assert(await page.locator('.react-flow__node.selected').count() > 0, 'marquee selects nodes')
  await page.mouse.click(830,810)
  await drag({x:820,y:790},{x:870,y:815},'middle')
  assert.notEqual(await viewport(), beforeViewport, 'middle drag pans')
  const middleViewport = await viewport()
  await page.keyboard.down('Space'); await drag({x:820,y:760},{x:850,y:780}); await page.keyboard.up('Space')
  assert.notEqual(await viewport(), middleViewport, 'Space drag pans')
  await page.getByRole('button',{name:'分组样例',exact:true}).click()
  await page.waitForTimeout(250)
  const childBefore = await node('texture').boundingBox(), groupBefore = await node('group').boundingBox()
  assert(childBefore && groupBefore)
  await drag({x:groupBefore.x+15,y:groupBefore.y+groupBefore.height-15},{x:groupBefore.x+75,y:groupBefore.y+groupBefore.height+25})
  const childAfter = await node('texture').boundingBox(), groupAfter = await node('group').boundingBox()
  assert(childAfter && groupAfter)
  assert(Math.abs((childAfter.x-childBefore.x)-(groupAfter.x-groupBefore.x))<1,'nested child follows parent once')
  assert(Math.abs((childAfter.y-childBefore.y)-(groupAfter.y-groupBefore.y))<1,'nested child y follows parent')
  await node('light').click()
  const toolbarBefore = await page.locator('.lab-node-toolbar').boundingBox()
  const lightBefore = await node('light').boundingBox()
  assert(toolbarBefore && lightBefore && toolbarBefore.y+toolbarBefore.height <= lightBefore.y,'toolbar belongs above selected node')
  await drag({x:lightBefore.x+100,y:lightBefore.y+65},{x:lightBefore.x+140,y:lightBefore.y+85})
  const toolbarAfter = await page.locator('.lab-node-toolbar').boundingBox()
  assert(toolbarAfter && toolbarAfter.x > toolbarBefore.x+20,'toolbar follows selected node')
  const handle = await node('light').locator('.react-flow__handle-right').boundingBox()
  const lightAfter = await node('light').boundingBox()
  assert(handle && lightAfter && Math.abs(handle.y+handle.height/2-lightAfter.y-lightAfter.height/2)<1,'fixed center anchor')
  await page.screenshot({path:`${output}/grouped-canvas.png`})
  await page.getByRole('button',{name:'200 / 300 基准',exact:true}).click()
  await page.waitForTimeout(400)
  assert.match(await page.locator('.lab-panel').innerText(),/200 节点 · 300 连线/)
  await page.getByRole('button',{name:'开始 10 分钟采样',exact:true}).click()
  await page.waitForTimeout(3000)
  await page.getByRole('button',{name:'停止并查看采样',exact:true}).click()
  await page.locator('output').filter({ hasText: /p95/ }).waitFor()
  assert.match(await page.locator('output').innerText(),/p95/)
  const sample = await page.locator('output').innerText()
  await page.screenshot({path:`${output}/benchmark.png`})
  await page.setViewportSize({width:390,height:844})
  await page.screenshot({path:`${output}/mobile.png`})
  assert(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),'mobile has no page overflow')
  assert.deepEqual(errors,[]); assert.deepEqual(apiRequests,[])
  await writeFile(`${output}/result.json`,JSON.stringify({pass:true,sample,errors,apiRequests,notes:'3秒技术样本，不是10分钟性能验收'},null,2))
  console.log(JSON.stringify({pass:true,sample,output}))
} finally { await browser.close() }
