// Real PostgreSQL/router/media fixture: TestCreativeBrowserPreview. Only refresh
// and /me authentication are stubbed; all creative and CRM requests hit the real server.
import assert from 'node:assert/strict'
import { readFileSync, writeFileSync } from 'node:fs'
import { join, resolve } from 'node:path'
import { chromium } from 'playwright'
const base = process.env.CREATIVE_BASE_URL ?? 'http://127.0.0.1:5178'
const out = process.env.CREATIVE_BROWSER_FIXTURE ?? '/tmp/creative-workspace-qa'
const { token } = JSON.parse(readFileSync(join(out, 'auth.json'), 'utf8'))
const browser = await chromium.launch()
const context = await browser.newContext({ viewport: { width: 1440, height: 1050 } })
await context.route('**/api/v1/auth/refresh', r => r.fulfill({ status:200, contentType:'application/json', body:JSON.stringify({access_token:token,token_type:'Bearer',expires_in:600}) }))
await context.route('**/api/v1/me', r => r.fulfill({status:200,contentType:'application/json',body:JSON.stringify({id:'creative-preview',email:'preview@example.invalid',created_at:'2026-09-07T00:00:00Z',timezone:'Asia/Shanghai'})}))
const page = await context.newPage(), errors = [], results = []
page.on('pageerror', e => errors.push(e.message))
const shot = name => page.screenshot({ path:join(out,name+'.png'),fullPage:true })
const button = name => page.getByRole('button',{name,exact:true})
const click = name => button(name).click()
try {
 await page.goto(base+'/creative-workspaces')
 await page.getByRole('heading',{name:'创意空间',exact:true}).waitFor()
 await page.waitForFunction(() => document.querySelector('.cw-onboarding') || [...document.querySelectorAll('button')].some(b=>b.textContent.includes('新建空间')))
 if (await button('检查并开启创意空间').isVisible()) await click('检查并开启创意空间')
 await button('＋ 新建空间').waitFor(); await shot('spaces-desktop'); await click('＋ 新建空间')
 await page.getByRole('heading',{name:'未命名空间',exact:true}).waitFor()
 const id=new URL(page.url()).pathname.split('/').at(-1)
 await page.getByLabel('把灵感放进来',{exact:true}).fill('窗边的安静时刻\nhttps://example.com/reference\n逆光下的轮廓')
 await page.locator('input[type=file]').setInputFiles([resolve('public/marketing/work-1.jpg'),resolve('public/marketing/work-2.jpg')])
 await click('搬入素材')
 await page.waitForFunction(()=>document.querySelectorAll('.cw-card').length===5)
 await page.locator('.cw-card img').first().waitFor(); await shot('wall-desktop')
 results.push('真实图片上传、多行成卡、服务端持久化5张素材')
 const cards=page.locator('.cw-card-main');await cards.nth(0).click();await cards.nth(1).click()
 await page.getByLabel('新分组',{exact:true}).fill('窗边');await click('成组')
 await page.waitForFunction(()=>!document.querySelector('.cw-selection'))
 await cards.nth(0).click();await cards.nth(2).click();await click('合成一个画面')
 await page.locator('.cw-shot').waitFor();await shot('shots-desktop');await click('进入现场 →')
 await page.locator('.cw-live-image img').waitFor()
 await click('✓ 拍完了');await button('撤销记录').waitFor();await click('撤销记录');await button('✓ 拍完了').waitFor();await click('这次跳过');await button('撤销记录').waitFor();await shot('live-desktop')
 results.push('图优先现场完成、撤销、跳过')
 await page.getByText('拍摄备忘 · 0',{exact:true}).click()
 await page.getByLabel('新增备忘，一行一条',{exact:true}).fill('备用电池\n反光板');await click('记下备忘')
 await page.locator('.cw-memo').first().waitFor();await page.getByLabel('备用电池',{exact:true}).click()
 await page.waitForFunction(()=>document.querySelector('.cw-memo .checked'))
 await page.setViewportSize({width:375,height:812});await shot('live-mobile')
 assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth+1),false,'375px overflow')
 await context.setOffline(true)
 await page.getByText('当前离线，清单可查看。完成、跳过和备忘尚不能保存。',{exact:true}).waitFor()
 assert.equal(await button('撤销记录').isDisabled(),true)
 await click('返回创作');await page.locator('.cw-card img').first().waitFor();await click('进入现场 →');await page.locator('.cw-live-image img').waitFor();await shot('live-offline-mobile')
 await context.setOffline(false);await page.waitForFunction(()=>!document.querySelector('.cw-live-actions > button')?.disabled)
 results.push('375px无横溢出、离线禁写、已加载图片可查看')
 await click('返回创作');await shot('wall-mobile')
 await page.getByText('空间名称与关联',{exact:true}).click();await page.getByLabel('空间名称',{exact:true}).fill('窗边人像');await click('保存名称')
 await page.getByRole('heading',{name:'窗边人像',exact:true}).waitFor()
 await page.getByLabel('选择关联').selectOption('ord_preview');await click('关联')
 await page.getByRole('link',{name:'窗边人像 ↗',exact:true}).click()
 await page.getByRole('link',{name:'创意空间 · 窗边人像 ↗',exact:true}).click()
 await page.getByRole('heading',{name:'窗边人像',exact:true}).waitFor();results.push('订单关联与双向跳转')
 await page.getByText('空间名称与关联',{exact:true}).click();await click('归档空间');await button('恢复空间').waitFor();await click('恢复空间');await button('搬入素材').waitFor()
 await page.reload();await page.waitForFunction(()=>document.querySelectorAll('.cw-card').length===5)
 results.push('归档恢复、刷新素材保留')
 await page.getByLabel('把灵感放进来',{exact:true}).fill('仍未保存的想法')
 await page.getByRole('link',{name:'← 所有空间',exact:true}).click()
 await page.getByRole('alertdialog').waitFor()
 await page.keyboard.press('Tab')
 assert.equal(await page.evaluate(()=>!!document.activeElement.closest('[role="alertdialog"]')),true,'dialog focus escaped')
 await page.keyboard.press('Escape')
 assert.equal(await page.getByLabel('把灵感放进来',{exact:true}).inputValue(),'仍未保存的想法')
 const importPath=`**/api/v1/creative-workspaces/${id}/cards`
 await context.route(importPath,async r=>{await r.fetch();await r.abort('failed')},{times:1})
 await click('搬入素材')
 await page.getByRole('alert').filter({hasText:'未能连接服务器'}).waitFor()
 assert.equal(await page.getByLabel('把灵感放进来',{exact:true}).inputValue(),'仍未保存的想法')
 await click('搬入素材')
 await page.waitForFunction(()=>document.querySelectorAll('.cw-card').length===6)
 results.push('未保存离开确认与键盘焦点、提交回执丢失后同键重试无重复素材')
 const data=await page.evaluate(async({id,token})=>(await fetch(`/api/v1/creative-workspaces/${id}`,{headers:{Authorization:`Bearer ${token}`}})).json(),{id,token})
 assert.equal(data.cards.length,6);assert.equal(data.shoot_items.length,1);assert.equal(data.memos.length,2);assert.deepEqual(errors,[])
 writeFileSync(join(out,'result.json'),JSON.stringify({passed:results,pageErrors:errors,spaceID:id,screenshotWidths:[1440,375]},null,2));console.log(JSON.stringify({passed:results,pageErrors:errors},null,2))
} catch(e){await shot('failure');console.error(e);process.exitCode=1}finally{await browser.close()}
